In [5]:
import numpy as np
def hwgroup(n,m):
    '''parameters:
    n - number of students to be grouped
    m - number of groups to be formed
    '''
    B=np.random.permutation(n)+1
    k=int(np.floor(n/m))
    r=n-m*k
    x=range(r,m)
    if r>0:
        for j in range(r):
            print(np.concatenate([B[(j*k):(k*(j+1))], B[m*k+j]],axis=None))
        for w in x:
            print(B[(w*k):(k*(w+1))])
    else: 
        for i in range(m):
            print(B[(i*k):(k*(i+1))])


In [6]:
hwgroup(19,4)

[ 1  5  4 16  2]
[11 13 12  6  8]
[ 3  7 19 18 14]
[17 15  9 10]
